name: Android Build APK

on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create client.properties
        run: |
          echo "ClientId=${{ secrets.CLIENT_ID }}" >> client.properties
          echo "ClientSecret=${{ secrets.CLIENT_SECRET }}" >> client.properties

      - run: |
           ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/release/*.apk
